Django_practice/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app"))
]

app/urls.py
from django.urls import path
from app.views import (
    MainPage,
    TagsListView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    TagCreateView,
    status_task_redirect,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", MainPage.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/status-change/", status_task_redirect, name="task-redirect")
]

app_name = "app"

todo_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls", namespace="todo_app"))
]

app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tags", blank=True, null=True, default=None)

    class Meta:
        ordering = ("status", )

    def __str__(self):
        return f"{self.content} ({self.created_date.strftime('%Y-%m-%d | %H:%M:%S')})"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>TODO</title>{% endblock %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          crossorigin="anonymous"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            crossorigin="anonymous"
            integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            crossorigin="anonymous"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            crossorigin="anonymous"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link rel="icon" href="{% static "to-do-list.png" %}">

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %} {% include "includes/sidebar.html" %} {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="tasks-info-title">
        <h1 class="task-info-text">
            TODO
            <a class="link-to-page btn btn-primary" href="{% url "task-form" %}">Create</a>
         </h1>
    </div>
    {% if task_list %}
        <div class="tasks">
            <hr>
            {% for task in task_list %}
                <div class="task-info">
                    <h4 class="task-name">
                        <b>{{ task.content }}</b>
                        <a class="btn btn-outline-danger link-to-page" href="{% url "task-delete" task.id %}">Delete</a>
                        <a class="btn btn-outline-secondary link-to-page" href="{% url  "task-update" task.id %}">Update</a>
                    </h4>
                    <p>
                        Created at: <b>{{ task.created_date.year }}/{{ task.created_date.month }}/{{ task.created_date.day }} {{ task.created_date.time }}</b>
                    </p>
                    {% if task.deadline %}
                        <p>Deadline: <b>{{ task.deadline.year }}/{{ task.deadline.month }}/{{ task.deadline.day }} {{ task.deadline.time }}</b></p>
                    {% else %}
                        <p>Deadline: <b>Unlimited</b></p>
                    {% endif %}
                    <p>
                        Tags: {% for tag in task.tags.all %}<b>{{ tag }}</b> | {% endfor %}
                    </p>
                    {% if not task.status %}
                        <a class="not-done" href="{% url "task-redirect" pk=task.id %}">
                            <span class="status-text-not-done">Not Done</span>
                            <span class="status-text-hover">Done!</span>
                        </a>
                    {% else %}
                        <a class="done" href="{% url "task-redirect" pk=task.id %}">
                            <span class="status-text-done">Done!</span>
                            <span class="status-text-not-done-button">Not Done</span>
                        </a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% block pagination %}{% include "includes/pagination.html" %}{% endblock %}
    {% else%}
        <hr>
        <h2>Empty task list...</h2>
    {% endif %}

{% endblock %}

templates/tag-delete-confirm.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
    <h1>Are you sure?You want delete <b>{{ tag.name }}</b> tag?</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <input type="submit" value="Delete" class="btn btn-danger">
            <input type="submit" value="Back" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

templates/tag-form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} tag</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/tags-list.html
{% extends "base.html" %}

{% block content %}
    <div class="tasks-info-title">
        <h1 class="task-info-text">
            Tags
            <a class="link-to-page btn btn-primary" href="{% url "tag-create" %}">Create</a>
        </h1>
    </div>
    <hr>
    {% if tag_list %}
        <table class="table">
            <tr>
                <th class="table-element table-title">Name</th>
                <th class="table-element table-title">Update</th>
                <th class="table-element table-title">Delete</th>
            </tr>
            {% for tag in tag_list %}
                <tr>
                    <td class="table-element table-el-name">{{ tag.name }}</td>
                    <td class="table-element"><a class="update-btn" href="{% url "tag-update" pk=tag.id %}">Update</a></td>
                    <td class="table-element"><a class="delete-btn" href="{% url "tag-delete" pk=tag.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>Empty tag list...</h3>
    {% endif %}
{% endblock %}

templates/task-delete-confirm-view.html
{% extends "base.html" %}
{% block content %}
    <h1>Are you sure you want to delete task:<b>{{ task.content }}</b>?</h1>
    <form action="" method="post">
        <br>
        {% csrf_token %}
        <div>
            <input class="btn btn-danger" type="submit" value="Delete">
            <input class="btn btn-primary" type="button" value="Cancel" onclick="history.back()">
        </div>
    </form>
{% endblock %}

templates/task-form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
    <h1 class="tasks-info-title task-info-text">{{ object|yesno:"Update,Create" }} task</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.media }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}